# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "trigger_jenkins"
  trigger_jenkins:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.JENKINS_CONTROLLER_URL }}
        user: ${{ secrets.JENKINS_TRIGGER_USER }}
        token: ${{ secrets.JENKINS_TRIGGER_TOKEN }}
        job: ${{ env.GITHUB_REPOSITORY }}
